[project]
name = "langgraph-agents"
version = "0.1.0"
description = "Creating different types of agents using langgraph"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-openrouter>=0.2.8",
    "langgraph>=1.2.11",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.15.0",
    "rich>=15.0.0",
]
